language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php: 5.5

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --verbose


branches:
  only:
    - master
    - dev